### ISSUE TITLE
Give audio uploads access to the targeted experience ID immediately after uploading

### ISSUE THREAD

**Issue by Awes-3** [blake-mealey/mantle#166]
**What type of feature request is this?**
Mantle doesn't support a Roblox feature I would like to use

Currently I have to manually give every audio asset uploaded access to the proper universe ID for them to play ingame without publishing a build, Ideally mantle should handle this for me, current workaround is going through every audio asset in the asset manager after deploying and clicking this in the output.
![Screenshot 2022-11-23 103805](https://user-images.githubusercontent.com/69554511/203587632-86a52901-a7ef-49c3-9d91-d27201f38f20.png)

**Comment by blake-mealey** [comment]
Thanks for flagging this! Is this related to a recent Roblox change? Was there an announcement post for it?

**Comment by eleanorlm** [comment]
> Is this related to a recent Roblox change? Was there an announcement post for it?

[Yes.](https://devforum.roblox.com/t/update-changes-to-asset-privacy-for-audio/1715717)

Relevant documentation: https://developer.roblox.com/en-us/articles/audio-asset-privacy

**Comment by blake-mealey** [comment]
This is fixed in the latest version (0.11.5)
