### ISSUE TITLE
Add support for .env files

### ISSUE THREAD

**Issue by TreehouseFalcon** [blake-mealey/mantle#169]
**What type of feature request is this?**
- [ ] Mantle doesn't support a Roblox feature I would like to use
- [x] Mantle CLI improvement
- [ ] Other

**Describe your problem**
Currently Mantle doesn't support loading remote state credentials without modifying your system user's AWS credentials file. This isn't scoped to the project you're working on and is a bit cumbersome.

**Describe the solution you'd like**
It would be great if Mantle could support loading remote state credentials (and any other environment-specific settings) via the industry-standard `.env` file.
Additionally, prefixing `.env` variable names with `MANTLE_` would allow other tools in the project to use different sets of AWS credentials.

**Comment by blake-mealey** [comment]
Just as a clarification, Mantle supports a few methods of AWS authentication including providing the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables.

I would like to add support for loading `.env` files for sure. As for the `MANTLE_` prefix, I think it's a good idea but I wouldn't want this to be a breaking change. Therefore, I'll have it look for `MANTLE_` prefixed variables first and then look for the current ones second.

Also a note to self: good opportunity to remove unnecessary rusoto credential methods (EC2-specific) and remove the timeout.

**Comment by blake-mealey** [comment]
Added in latest version: 0.11.6
