### ISSUE TITLE
Updating existing audio with mantle deploy does not give audio permissions to experience

### ISSUE THREAD

**Issue by Awes-3** [blake-mealey/mantle#171]
Creating a new audio will properly give the asset permission to play in the desired target experience, however updating an audio asset that already exists in the mantle state file (e.g. hash difference from editing an audio clip) does not appear to do the same.
(This includes audio that was previously given permission when it was initially uploaded by mantle; when editing that file and re-deploying, audio permissions are stripped)

**Comment by blake-mealey** [comment]
Thanks for reporting, will take a look

**Comment by blake-mealey** [comment]
Fix merged, will let you know when a new version is released.

**Comment by blake-mealey** [comment]
Fixed in latest version: 0.11.6
