### ISSUE TITLE
Support hybrid Open Cloud usage to reduce dependence on cookies

### ISSUE THREAD

**Issue by blake-mealey** [blake-mealey/mantle#179]
Some users are experiencing issues with cookies getting cancelled by Roblox. This makes CI integrations harder to manage. We can introduce a hybrid setup so that if an Open Cloud token is available, Mantle will use it for operations that it supports. Mantle will still require cookie auth for many APIs but since the most common API it uses is probably the place upload API, this should significantly help users with CI stability.

**Comment by GreenAppers** [comment]
For a possible workaround, see https://github.com/marketplace/actions/savetoroblox

**Comment by blake-mealey** [comment]
This was implemented in [v0.11.15](https://github.com/blake-mealey/mantle/releases/tag/v0.11.15)
