### ISSUE TITLE
Export mantle environment in outputs

### ISSUE THREAD

**Issue by Awes-3** [blake-mealey/mantle#182]
**What type of feature request is this?**
- [ ] Mantle doesn't support a Roblox feature I would like to use
- [x] Mantle CLI improvement
- [ ] Other

**Describe your problem**
I would like to expose different features of my game depending on what environment the game was deployed from. An example would be letting a "QA Tester" role in a group access a debug menu in a development environment, but restricting access to that menu in production.

**Describe the solution you'd like**
Mantle could export the environment you are deploying from in the outputs JSON file.

**Comment by blake-mealey** [comment]
Good idea, I've updated https://github.com/blake-mealey/mantle/issues/132 to include this
