### ISSUE TITLE
Add `-quiet` flag to `mantle outputs`

### ISSUE THREAD

**Issue by TreehouseFalcon** [blake-mealey/mantle#200]
**Describe your problem**

I use Mantle in a runtime environment at startup and currently have to save resource outputs to a file (`mantle outputs -o`). This can be cumbersome and would be much easier and more efficient if we could pipe or read outputs instead of saving them to a file. I can't easily use `mantle outputs` because there's logging information printed at the beginning of the execution.

**Describe the solution you'd like**

Having a `-quiet` (`-q`) flag to turn off logging for successful operations would be nice.

**Comment by blake-mealey** [comment]
I agree this should be improved. I think rather than adding a quiet mode I would like to write the other text to stderr so that it doesn't affect the output. This aligns with standard best practice for CLIs.

**Comment by blake-mealey** [comment]
This has been fixed in v0.11.12
