### ISSUE TITLE
CLI failing to import a project

### ISSUE THREAD

**Issue by Etheroit** [blake-mealey/mantle#209]
**Describe the bug**
I'm trying to add import a project using `mantle import` command documented at https://mantledeploy.vercel.app/docs/commands#importing .

The command seems to be failing on "Importing passes" stage with "Failed: Roblox error (500 Internal Server Error): InternalServerError"

**To Reproduce**
To reproduce the behaviour, use `mantle import --environment prod --target-id`. The experience I've used the command on had no passes available.

**Screenshots**
![image](https://github.com/blake-mealey/mantle/assets/42714242/f6035a81-4206-44dd-a53c-dfef6a477553)

**Comment by blake-mealey** [comment]
This should be fixed in v0.11.13. Let me know if upgrading doesn't fix the issue.

**Comment by Etheroit** [comment]
> This should be fixed in v0.11.13. Let me know if upgrading doesn't fix the issue.

It's working thanks. Not sure why I've thought 0.11.11 was the latest version. My fault.
