### ISSUE TITLE
Add an `owner` override for environments

### ISSUE THREAD

**Issue by SolarHorizon** [blake-mealey/mantle#215]
**What type of feature request is this?**
- [ ] Mantle doesn't support a Roblox feature I would like to use
- [x] Mantle CLI improvement
- [ ] Other

**Describe your problem**
My game uses two different groups. One is for developers and the other is for the community. We use the developer group to host our staging environment for testing and the other group has the live game. Since ownership is configured globally, it makes it difficult for us to use Mantle.

**Describe the solution you'd like**
It'd be nice if we could override `owner` and `payments` based on the environment.

**Comment by blake-mealey** [comment]
Thanks for the feedback! Do you think this would be a good solution for you? https://github.com/blake-mealey/mantle/issues/147

**Comment by SolarHorizon** [comment]
If variables are able to be used anywhere in your configuration that'd be awesome. That would definitely solve my problem.

**Comment by blake-mealey** [comment]
Yup the idea would be to have variables be usable anywhere in the config file

**Comment by blake-mealey** [comment]
Closing as part of #147
