### ISSUE TITLE
Place upload endpoint is deprecated, causing unclear 'file may be too large' errors

### ISSUE THREAD

**Issue by autonordev** [blake-mealey/mantle#224]
In my project, I was experiencing an error with place files not uploading correctly.

```
Failed: Place file size may be too large.
```

This was after a heavy but essential model was added to the source tree, so I assumed it to be that. However, uploading in studio still worked fine. Removing the heavy model still results in this error though.

Investigating this further, I attempted to upload via Rojo using an Open Cloud key; this upload was successful. I tried uploading via Rojo using a cookie instead, and got this output:

![image](https://github.com/user-attachments/assets/80d0155b-9f36-4695-b8c6-7baa94337bad)

It seems like both [Rojo](https://github.com/rojo-rbx/rojo/blob/30f439caec3be30ac9e0954e6c889415ee804efd/src/cli/upload.rs#L122) and [Mantle](https://github.com/blake-mealey/mantle/blob/f1ef4e6ad66cf6e04b8287dfbb0730ebfdf9d4be/mantle/rbx_api/src/places/mod.rs#L50) upload via the same endpoint. Although Rojo does provide different headers.

This makes me suspect that Roblox are possibly killing the endpoint in an A/B test.

**Environment (please complete the following information):**
 - OS: Windows 11
 - Mantle Version 0.11.16

**Comment by blake-mealey** [comment]
A fix for this was implemented in [v0.11.15](https://github.com/blake-mealey/mantle/releases/tag/v0.11.15) by adding support for the Open Cloud Place Publishing API. View the release for more details.
